### ISSUE TITLE
Missing .exe folder

### ISSUE THREAD

**Issue by simonamigl** [KRichardsF/Hough-Scan#2]

**Comment by ChemistKieran** [comment]
Hi, 
The latest version with an exe. is under pre-release section. 
It's a bit old now though - I'll hopefully release a more up to date version later this year.

**Comment by simonamigl** [comment]
HI Kieran,

Thank you for your answer. I did find the old version, however when I try
to run it it gives me a series of errors apparently because it can't find
libpython3.8.dll.
Do you how to fix this issue?

Thank you very much.

Best wishes,
Simona

**Comment by ChemistKieran** [comment]
Hi Simona, 

The only thing I can think of is that something's gone wrong while extracting the files and some of the .dll files have gone missing.

Try re-extracting the .zip file and running the .exe file in the folder. 

Let me know if you have any other issues (there's likely to be a few bugs).
